%% WaveformGenerator
% Example for algorithm WaveformGenerator
%
% WaveformGenerator is an algorithm for complex waveform generating.

%% Set acquisition properties
% First acquisition quantities are prepared: sampling frequency |fs| set to 
% 10 kHz, and length of the record |L| set to 1000, representing 0.1 s long record.
DI = [];
DI.fs.v = 1e4;
DI.L.v = 1e3;

%% Set waveform properties
% The actual waveform will consist of 3 signal components. Main signal
% component frequency will be 50 Hz, amplitude 1 V. Third harmonic amplitude
% will be set to 0.15 V. Last component will be interharmonic of frequency 79 Hz and amplitude of 0.1 V.
DI.f.v =  [50  150 757];
DI.A.v =  [ 1 0.15 0.05];
DI.ph.v = [ 0    0   0];

%% Call algorithm
% Use QWTB to apply algorithm |WaveformGenerator| to data |DI|.
CS.verbose = 1;
DO = qwtb('WaveformGenerator', DI, CS);

%% Display results
% Results are the time stamps and samples.
plot(DO.t.v, DO.y.v, '-+')
xlabel('t (s)')
title('Waveform generated by WaveformGenerator algorithm')
