#!/bin/bash
dot -Tsvg inner_flowchart.dot -o inner_flowchart.svg
dot -Tsvg outer_flowchart.dot -o outer_flowchart.svg
dot -Tpdf inner_flowchart.dot -o inner_flowchart.pdf
dot -Tpdf outer_flowchart.dot -o outer_flowchart.pdf
