Description of rms
Home > adctest_v43 > rms.m
rms
PURPOSE
SYNOPSIS
function y = rms(x)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CompareLSvsML @fn CompareLSvsML
DisplayResultsLS4p @fn DisplayResultsLS4p
ProcessDscML5pFit @fn ProcessDscML5pFit
SOURCE CODE
function y = rms(x)
x = x(:);
y = sqrt(1/length(x)*x.'*x);
end