#!/bin/bash

# omit repeated lines (otherwise the graph is bad)
perl -n -e 'print unless $h{$_}++' deptmp/graph.dot > deptmp/uniq.dot
# if you dont't have perl, you can use (warning change the order of the lines)
# sort deptmp/graph.dot >  deptmp/sort.dot
# uniq deptmp/sort.dot >  deptmp/uniq.dot

# put the header for the .dot file
echo "/* Generated by dep */" > $1.dot
echo "digraph dep {" >> $1.dot
echo "    node [shape = box];" >> $1.dot

# other options
# fontsize = 360;
# orientation=landscape;
# ratio=fill;
# size="11,7";
# node [shape = box, style = filled,peripheries=1,fontsize=80];
# nodesep=0.9;
# ranksep=2;

# put the content
cat deptmp/uniq.dot >> $1.dot

# end of the .dot file
echo "}" >> $1.dot

# run dot
dot -Tpdf $1.dot -o $1.pdf

exit 0;
